---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"password","client_id":"app-12345","username":"jason.null@brightbox.com","password":"N:B3e%7Cmh"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '136'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"238b4c855009fc568ff165c6ecef13a2"'
      X-Request-Id:
      - 284d62b734d307a10e9c2ddee917eff2
      X-Runtime:
      - '0.272491'
      Date:
      - Tue, 03 Sep 2013 08:23:49 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"249a267eece280b596f47dbe5769804b14ea5b41","expires_in":7200,"refresh_token":"061c989938c5e277a2ec95fee9fe25b077935fce"}'
    http_version: 
  recorded_at: Tue, 03 Sep 2013 08:23:49 GMT
recorded_with: VCR 2.5.0
