---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"none","client_id":"cli-12345"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic Y2xpLTEyMzQ1OnF5Nnh4bnZ5NG8wdGd2NQ==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '77'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"430906f14dbb1d6e1227c369fbbc9f05"'
      X-Request-Id:
      - 8c2cd78990e554ee6df5b57df9f3babf
      X-Runtime:
      - '0.237022'
      Date:
      - Fri, 06 Sep 2013 15:58:58 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"67e22969d707ebaf5590272b5e64dc4ed9b31fdd","expires_in":7200}'
    http_version: 
  recorded_at: Fri, 06 Sep 2013 15:58:58 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/account
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - OAuth 0ab4badeb10018d07c1f6c33690ee011f36b4183
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json; charset=utf-8
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"a9e93d5f3268805675b0c5c935311a85"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - b4edcfd134f91075932a85564772e730
      X-Runtime:
      - '0.116152'
      Date:
      - Fri, 06 Sep 2013 15:58:58 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"Aurnqfvgsbeyiprni","status":"active","address_1":"Kaycee
        Throughway","address_2":"","city":"South Hellenport","county":"","postcode":"60364-9886","country_code":"GB","country_name":"United
        Kingdom","vat_registration_number":"","telephone_number":"+444238318140","telephone_verified":false,"verified_telephone":null,"verified_at":null,"verified_ip":null,"created_at":"2013-09-04T07:53:13Z","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"valid_credit_card":false,"library_ftp_host":"ftp.library.gb1.brightbox.com","library_ftp_user":"acc-12345","library_ftp_password":null,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"56.67.59.219","reverse_dns":"cip-12345-67-59-219.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-04T07:53:13Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-04T07:53:14Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Dylan
        Fay DDS","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}'
    http_version: 
  recorded_at: Fri, 06 Sep 2013 15:58:58 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - OAuth 67e22969d707ebaf5590272b5e64dc4ed9b31fdd
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: 
    headers:
      WWW-Authenticate:
      - OAuth error="invalid_token"
      Content-Type:
      - application/json; charset=utf-8
      X-UA-Compatible:
      - IE=Edge
      Cache-Control:
      - no-cache
      X-Request-Id:
      - 14082450ec1ec70923bc9c91e9adce53
      X-Runtime:
      - '0.017801'
      Date:
      - Tue, 17 Sep 2013 17:07:36 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"error":"invalid_token","error_description":"The OAuth token can not
        be found"}'
    http_version: 
  recorded_at: Tue, 17 Sep 2013 17:07:36 GMT
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"none","client_id":"cli-12345"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic Y2xpLTEyMzQ1OnF5Nnh4bnZ5NG8wdGd2NQ==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '77'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"c0dd0bb66771d924e5b9d845a8f5b6a4"'
      X-Request-Id:
      - b7a48ca0b5632951eaf7464ca0698b08
      X-Runtime:
      - '0.111296'
      Date:
      - Tue, 17 Sep 2013 17:07:36 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"316f5c33ab293daeb01b759fa32fe758ef1cccc0","expires_in":7200}'
    http_version: 
  recorded_at: Tue, 17 Sep 2013 17:07:36 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - OAuth 316f5c33ab293daeb01b759fa32fe758ef1cccc0
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json; charset=utf-8
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"7d4ad7857ea408897b8a2149197611ba"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 7f4fd962f1dc00a3b1bfdd6e4d81a36f
      X-Runtime:
      - '0.255430'
      Date:
      - Tue, 17 Sep 2013 17:07:37 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '[{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"Asaibdsjnpdgrdcqo","status":"active","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"153.37.92.121","reverse_dns":"cip-12345-37-92-121.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-17T08:44:16Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-17T08:44:16Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Kobe
        Swaniawski Sr.","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version: 
  recorded_at: Tue, 17 Sep 2013 17:07:37 GMT
recorded_with: VCR 2.5.0
