---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"password","client_id":"app-12345","username":"jason.null@brightbox.com","password":"N:B3e%7Cmh"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '136'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"ca48bf9e5274e6d445ffc2311650a091"'
      X-Request-Id:
      - 00651ace47c9cf3336074e93cca64e34
      X-Runtime:
      - '0.201773'
      Date:
      - Tue, 27 Aug 2013 16:51:30 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"f81477becc6b5ed36063461ba02466c25c07ce99","expires_in":7200,"refresh_token":"ad9aa1f13fc478ee6408372a92b8bbbfa80830b8"}'
    http_version: 
  recorded_at: Tue, 27 Aug 2013 16:51:30 GMT
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"none","client_id":"cli-12345"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic Y2xpLTEyMzQ1OnF5Nnh4bnZ5NG8wdGd2NQ==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '77'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"66d8a5c29fa00316dcf174034bb3f8e3"'
      X-Request-Id:
      - 95daa19688abf69ad3af10f1e216fc2e
      X-Runtime:
      - '1.187585'
      Date:
      - Tue, 03 Sep 2013 10:17:25 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"2245493c9aa7dc11e7b8d99d1ef27bcb5b1ffd6f","expires_in":7200}'
    http_version: 
  recorded_at: Tue, 03 Sep 2013 10:17:25 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - OAuth 2245493c9aa7dc11e7b8d99d1ef27bcb5b1ffd6f
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json; charset=utf-8
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"4cc29facf432e8f6272a32e38cabd4d8"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a39109be5aad2683d7030dd5e89644e9
      X-Runtime:
      - '2.554067'
      Date:
      - Tue, 03 Sep 2013 10:17:28 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '[{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"Ajusebltwarlwxdux","status":"active","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"59.168.156.224","reverse_dns":"cip-12345-168-156-224.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-02T13:41:44Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-02T13:41:44Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Cordell
        Fay","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version: 
  recorded_at: Tue, 03 Sep 2013 10:17:28 GMT
recorded_with: VCR 2.5.0
